src/doctor/routes.py
import os
from src import db, hash_manager
from src.public.utils import (
    get_datetime,
    profile_picture_remover,
    profile_picture_saver,
)
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    flash,
    abort,
    request,
    jsonify,
    current_app,
    send_file,
)
from flask_login import login_required, current_user
from src.users.models import Users, User_Logs, Doctors, Patients, Managers
from src.patient.models import (
    Medical_Info,
    Medical_Report_Files,
    Medical_Test_Book,
    Invoices,
    Invoice_Items,
    Patient_Record_Files,
)
from src.doctor.models import Doctor_Time
from src.doctor.models import (
    Appointments,
    Appointment_Details,
    Prescriptions,
    Prescription_Extras,
    Prescribed_Items,
)
from src.doctor.forms import (
    UpdateProfileForm,
    ChangePasswordForm,
    UpdateScheduleForm,
    PresItemForm,
    PresEditItemForm,
)


doctor = Blueprint("doctor", __name__)


@doctor.route("/dashboard/doctor")
@login_required
def dashboard():
    if current_user.role != "Doctor":
        abort(403)

    user = (
        Doctors.query.filter(Doctors.d_id == current_user.id)
        .join(Users, Doctors.d_id == Users.id)
        .join(Doctor_Time, Doctor_Time.doctor_id == Doctors.d_id)
        .add_columns(
            Users.username,
            Users.gender,
            Users.email,
            Doctors.title,
            Doctors.first_name,
            Doctors.last_name,
            Doctors.phone,
            Doctors.birthdate,
            Doctors.avatar,
            Doctor_Time.appt_status,
        )
        .first()
    )

    pending_count = (
        Appointments.query.filter(Appointments.appt_doctor_id == current_user.id)
        .join(Appointment_Details, Appointment_Details.appt_id == Appointments.appt_id)
        .filter(Appointment_Details.appt_status == "Booked")
        .count()
    )

    ip = request.remote_addr
    info = request.headers.get("User-Agent")

    return render_template(
        "doctor/dashboard.html",
        user=user,
        pending=pending_count,
        ip=ip,
        info=info,
        title="Dashboard",
    )


@doctor.route("/dashboard/doctor/change_status")
@login_required
def change_appt_status():
    if current_user.role != "Doctor":
        abort(403)

    doctor_time: Doctor_Time = Doctor_Time.query.filter(
        Doctor_Time.doctor_id == current_user.id
    ).first_or_404()

    if doctor_time.appt_status == "Available":
        doctor_time.appt_status = "Unavailable"
    else:
        doctor_time.appt_status = "Available"

    date, time = get_datetime()
    new_log = User_Logs(current_user.id, "Change Status", date, time)
    db.session.add(new_log)
    db.session.commit()

    flash("Status Changed Successfully!", category="success")
    return redirect(url_for("doctor.dashboard"))


@doctor.route("/dashboard/doctor/patients")
@login_required
def patients():
    if current_user.role != "Doctor":
        abort(403)

    page_num = request.args.get("page", 1, int)

    patients = (
        Patients.query.join(Appointments, Appointments.appt_patient_id == Patients.p_id)
        .filter(Appointments.appt_doctor_id == current_user.id)
        .join(Appointment_Details, Appointment_Details.appt_id == Appointments.appt_id)
        .filter(Appointment_Details.appt_status == "Completed")
        .join(Users, Users.id == Patients.p_id)
        .add_columns(
            Patients.p_id,
            Patients.last_name,
            Patients.first_name,
            Patients.phone,
            Patients.birthdate,
            Patients.avatar,
            Users.gender,
        )
        .paginate(page=page_num, per_page=12)
    )
    return render_template(
        "doctor/patients.html", patients=patients, title="My Patients"
    )


@doctor.route("/dashboard/doctor/patients/<patient_id>")
@login_required
def view_patient(patient_id):
    if current_user.role != "Doctor":
        abort(403)

    page_num = request.args.get("page", 1, int)

    patient: Patients = (
        Patients.query.filter(Patients.p_id == int(patient_id))
        .join(Users, Users.id == Patients.p_id)
        .join(Medical_Info, Medical_Info.patient_id == Patients.p_id)
        .add_columns(
            Patients.p_id,
            Patients.last_name,
            Patients.first_name,
            Patients.phone,
            Patients.birthdate,
            Patients.avatar,
            Users.gender,
            Users.email,
            Medical_Info.blood_group,
            Medical_Info.height_cm,
            Medical_Info.weight_kg,
            Medical_Info.allergies,
            Medical_Info.medical_conditions,
        )
        .first_or_404()
    )

    files: Patient_Record_Files = (
        Patient_Record_Files.query.filter(
            Patient_Record_Files.record_patient_id == int(patient_id)
        )
        .order_by(Patient_Record_Files.file_id.desc())
        .paginate(page=page_num, per_page=10)
    )

    return render_template(
        "doctor/view_patient.html",
        patient=patient,
        files=files,
        title=f"Patient {patient.last_name} {patient.first_name}",
    )


@doctor.route("/dashboard/doctor/patients/<patient_id>/appointments")
@login_required
def view_patient_appointments(patient_id):
    if current_user.role != "Doctor":
        abort(403)

    page_num = request.args.get("page", 1, int)

    patient: Patients = Patients.query.filter(
        Patients.p_id == int(patient_id)
    ).first_or_404()
    appointments = (
        Appointments.query.filter(Appointments.appt_patient_id == patient.p_id)
        .join(Appointment_Details, Appointment_Details.appt_id == Appointments.appt_id)
        .filter(Appointment_Details.appt_status == "Completed")
        .join(Doctors, Appointments.appt_doctor_id == Doctors.d_id)
        .join(Users, Users.id == Doctors.d_id)
        .order_by(Appointment_Details.appt_date.desc())
        .add_columns(
            Appointments.appt_id,
            Appointment_Details.appt_status,
            Appointment_Details.appt_date,
            Appointment_Details.appt_time,
            Doctors.d_id,
            Doctors.last_name,
            Doctors.first_name,
            Doctors.title,
            Doctors.avatar,
            Users.gender,
        )
        .paginate(page=page_num, per_page=10)
    )

    return render_template(
        "doctor/patient_appointments.html",
        patient=patient,
        appointments=appointments,
        title=f"Patient Appointment History",
    )


@doctor.route("/dashboard/doctor/patients/<patient_id>/tests")
@login_required
def view_patient_tests(patient_id):
    if current_user.role != "Doctor":
        abort(403)

    page_num = request.args.get("page", 1, int)

    patient: Patients = Patients.query.filter(
        Patients.p_id == int(patient_id)
    ).first_or_404()
    tests = (
        Medical_Test_Book.query.filter(
            Medical_Test_Book.test_patient_id == Patients.p_id
        )
        .filter(Medical_Test_Book.test_patient_id == patient.p_id)
        .filter(Medical_Test_Book.test_status == "Done")
        .join(Invoice_Items, Invoice_Items.item_id == Medical_Test_Book.invoice_item_id)
        .join(Invoices, Invoices.invoice_id == Invoice_Items.invoice_id)
        .order_by(Invoices.invoice_date.desc())
        .add_columns(
            Medical_Test_Book.serial_number,
            Invoice_Items.item_desc,
            Invoices.invoice_date,
        )
        .paginate(page=page_num, per_page=12)
    )

    return render_template(
        "doctor/patient_test_history.html",
        patient=patient,
        tests=tests,
        title=f"Patient Medical Tests",
    )


@doctor.route("/dashboard/doctor/patients/<patient_id>/test_file/<file_id>")
@login_required
def view_patient_test_file(patient_id, file_id):
    if current_user.role != "Doctor":
        abort(403)

    patient = Patients.query.filter(Patients.p_id == int(patient_id)).first_or_404()
    file = (
        Medical_Report_Files.query.filter(Medical_Report_Files.file_id == int(file_id))
        .join(
            Medical_Test_Book,
            Medical_Report_Files.test_book_serial == Medical_Test_Book.serial_number,
        )
        .join(Managers, Medical_Report_Files.upload_manager_id == Managers.m_id)
        .add_columns(
            Medical_Report_Files.file_id,
            Medical_Report_Files.file_name,
            Medical_Report_Files.file_path_name,
            Medical_Report_Files.file_size_kb,
            Medical_Report_Files.upload_date,
            Medical_Report_Files.upload_time,
            Medical_Report_Files.test_book_serial,
            Managers.first_name,
            Managers.last_name,
        )
        .first_or_404()
    )

    return render_template(
        "doctor/patient_test_file_view.html",
        title=f"Report: {file.file_name}",
        file=file,
        patient=patient,
    )


@doctor.route("/dashboard/doctor/patients/<patient_id>/test_files/<file_id>/download")
@login_required
def download_patient_test_file(patient_id, file_id):
    if current_user.role != "Doctor":
        abort(403)

    file: Medical_Report_Files = Medical_Report_Files.query.filter(
        Medical_Report_Files.file_id == int(file_id)
    ).first_or_404()

    file_name = f"{file.file_name}_{file.file_path_name}"
    return send_file(
        os.path.join(
            current_app.root_path,
            "static/upload/manager/test_results/",
            file.file_path_name,
        ),
        download_name=file_name,
        as_attachment=True,
    )


@doctor.route("/dashboard/doctor/patients/<patient_id>/records/<file_id>")
@login_required
def view_patient_record_file(patient_id, file_id):
    if current_user.role != "Doctor":
        abort(403)

    patient = Patients.query.filter(Patients.p_id == int(patient_id)).first_or_404()
    file: Patient_Record_Files = Patient_Record_Files.query.filter(

src/templates/layout/layout_doctor.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>MediPlus - {{ title }}</title>
    {% else %}
    <title>MediPlus</title>
    {% endif %}
    <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='32' height='32' fill='%23198754' viewBox='0 0 16 16'%3E%3Cpath
        d='M1.475 9C2.702 10.84 4.779 12.871 8 15c3.221-2.129 5.298-4.16 6.525-6H12a.5.5 0 0 1-.464-.314l-1.457-3.642-1.598
        5.593a.5.5 0 0 1-.945.049L5.889 6.568l-1.473 2.21A.5.5 0 0 1 4 9z'/%3E%3Cpath d='M.88 8C-2.427 1.68 4.41-2 7.823
        1.143q.09.083.176.171a3 3 0 0 1 .176-.17C11.59-2 18.426 1.68 15.12 8h-2.783l-1.874-4.686a.5.5 0 0 0-.945.049L7.921 8.956
        6.464 5.314a.5.5 0 0 0-.88-.091L3.732 8z'/%3E%3C/svg%3E" />

    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap-icons.min.css')}}">
    <!-- JS -->
    <script type="text/javascript" src="{{url_for('static', filename='js/jquery-3.7.1.min.js') }}"></script>
</head>

<body class="bg-light-subtle">
    <nav class="navbar navbar-expand-md bg-info-subtle">
        <div class="container">
            <a class="navbar-brand fs-5" href="{{ url_for('public.index')}}">
                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="#198754" viewBox="0 0 16 16">
                    <path
                        d="M1.475 9C2.702 10.84 4.779 12.871 8 15c3.221-2.129 5.298-4.16 6.525-6H12a.5.5 0 0 1-.464-.314l-1.457-3.642-1.598 5.593a.5.5 0 0 1-.945.049L5.889 6.568l-1.473 2.21A.5.5 0 0 1 4 9z" />
                    <path
                        d="M.88 8C-2.427 1.68 4.41-2 7.823 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C11.59-2 18.426 1.68 15.12 8h-2.783l-1.874-4.686a.5.5 0 0 0-.945.049L7.921 8.956 6.464 5.314a.5.5 0 0 0-.88-.091L3.732 8z" />
                </svg>
                <b class="text-danger">Medi</b><b class="text-success">Plus</b>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#topNavbar"
                aria-controls="topNavbar" aria-expanded="false">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="topNavbar">
                <ul class="navbar-nav nav-underline ms-auto mb-2 mb-lg-0 fw-semibold">
                    <li class="nav-item">
                        <a class="nav-link text-info" id="navDashboard" href="{{ url_for('public.dashboard') }}">
                            Dashboard
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-info" id="navPat" href="{{ url_for('doctor.patients') }}">
                            Patients
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-info" id="navAppt" href="{{ url_for('doctor.appointments') }}">
                            Appointments
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link text-info dropdown-toggle" id="navAccount" data-bs-toggle="dropdown" href="#"
                            role="button" aria-expanded="false">
                            Account
                        </a>
                        <ul class="dropdown-menu bg-info bg-opacity-10">
                            <li>
                                <a class="dropdown-item" id="navProfile" href="{{ url_for('doctor.profile') }}">
                                    Edit Profile
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" id="navSchedule" href="{{ url_for('doctor.update_schedule') }}">
                                    Update Schedule
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" id="navLogs" href="{{ url_for('doctor.logs') }}">
                                    Account Logs
                                </a>
                            </li>
                                <hr class="dropdown-divider">
                            <li>
                                <a class="dropdown-item text-danger" href="{{ url_for('public.logout') }}">
                                    Logout
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Notice section start -->
    <div class="clearfix mt-3 ms-2 me-2">
        <div class="mx-auto" style="max-width: 500px;">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible text-center mb-2 fw-bold" fade show>
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </div>
    <!-- Notice section end -->

    {% block content %}

    {% endblock content %}

    <!-- JS -->
    <script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.bundle.min.js')}}"></script>
</body>

</html>

src/templates/layout/layout_manager.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" , shrink-to-fit="no">
    {% if title %}
    <title>MediPlus - {{ title }}</title>
    {% else %}
    <title>MediPlus</title>
    {% endif %}

    <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='32' height='32' fill='%23198754' viewBox='0 0 16 16'%3E%3Cpath
    d='M1.475 9C2.702 10.84 4.779 12.871 8 15c3.221-2.129 5.298-4.16 6.525-6H12a.5.5 0 0 1-.464-.314l-1.457-3.642-1.598
    5.593a.5.5 0 0 1-.945.049L5.889 6.568l-1.473 2.21A.5.5 0 0 1 4 9z'/%3E%3Cpath d='M.88 8C-2.427 1.68 4.41-2 7.823
    1.143q.09.083.176.171a3 3 0 0 1 .176-.17C11.59-2 18.426 1.68 15.12 8h-2.783l-1.874-4.686a.5.5 0 0 0-.945.049L7.921 8.956
    6.464 5.314a.5.5 0 0 0-.88-.091L3.732 8z'/%3E%3C/svg%3E" />

    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap-icons.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='mycss/mg_board.css')}}">
    <!-- JS -->
    <script type="text/javascript" src="{{url_for('static', filename='js/jquery-3.7.1.min.js') }}"></script>
    <script src="{{url_for('static', filename='js/plotly-2.31.1.min.js') }}" charset="utf-8"></script>
</head>

<body class="bg-light-subtle">
    <main class="wrapper" role="main">
        <aside class="sidebar p-3 bg-body-secondary">
            <div class="d-flex flex-column">
                <a class="navbar-brand me-3" href="{{ url_for('public.index') }}">
                    <i class="bi bi-heart-pulse-fill text-success fs-5"></i>
                    <span class="fs-4 d-none d-sm-inline">
                        <b class="text-danger">Medi</b><b class="text-success">Plus</b>
                    </span>
                </a>

                <hr>
                <div class="navbar-brand mb-3">
                    <a href="{{ url_for('manager.account') }}" class="text-decoration-none text-success">
                    <img src="{{ url_for('static', filename='avatars/manager/'~session['avatar']) }}" width="50" height="50"
                        class="rounded-circle mt-2 float-start" alt="{{ current_user.username }}">
                    <div class="fs-5 d-none d-sm-inline ps-3">
                            {{ current_user.username }}
                        </div>
                    </a>
                    <br>
                    <div class="small text-secondary d-none d-sm-inline ps-3">
                        {{ current_user.role }}
                    </div>
                </div>

                <!-- Sidebar Options Start -->
                <ul class="nav flex-column me-3">
                    <li class="nav-item mb-2">
                        <a href="{{ url_for('public.dashboard') }}"
                            class="navbar-brand nav-link text-success rounded p-2" id="side_overview">
                            <i class="bi bi-file-earmark-bar-graph"></i>
                            <span class="ps-1 fs-5 d-none d-sm-inline">Overview</span>
                        </a>
                    </li>

                    <li class="nav-item mb-2">
                        <a href="{{ url_for('manager.appointments') }}"
                            class="navbar-brand nav-link text-success rounded p-2" id="side_appointments">
                            <i class="bi bi-calendar-plus"></i>
                            <span class="ps-1 fs-5 d-none d-sm-inline">Appointments</span>
                        </a>
                    </li>

                    <li class="nav-item mb-2">
                        <a href="{{ url_for('manager.tests') }}"
                            class="navbar-brand nav-link text-success rounded p-2" id="side_tests">
                            <i class="bi bi-clipboard2-pulse"></i>
                            <span class="ps-1 fs-5 d-none d-sm-inline">Medical Tests</span>
                        </a>
                    </li>

                    <li class="nav-item mb-2">
                        <a href="{{ url_for('manager.invoices') }}"
                            class="navbar-brand nav-link text-success rounded p-2" id="side_invoices">
                            <i class="bi bi-receipt"></i>
                            <span class="ps-1 fs-5 d-none d-sm-inline">Invoices</span>
                        </a>
                    </li>

                    <li class="nav-item mb-2">
                        <a href="{{ url_for('manager.patients') }}"
                            class="navbar-brand nav-link text-success rounded p-2" id="side_patient">
                            <i class="bi bi-person-wheelchair"></i>
                            <span class="ps-1 fs-5 d-none d-sm-inline">Patients</span>
                        </a>
                    </li>

                    <li class="nav-item mb-2">
                        <a href="{{ url_for('manager.doctors') }}"
                            class="navbar-brand nav-link text-success rounded p-2" id="side_doctor">
                            <i class="bi bi-person-fill-add"></i>
                            <span class="ps-1 fs-5 d-none d-sm-inline">Doctors</span>
                        </a>
                    </li>

                    <li class="nav-item mb-2">
                        <a href="{{ url_for('manager.managers') }}"
                            class="navbar-brand nav-link text-success rounded p-2" id="side_manager">
                            <i class="bi bi-person-fill-gear"></i>
                            <span class="ps-1 fs-5 d-none d-sm-inline">Managers</span>
                        </a>
                    </li>

                    <li class="nav-item mb-2">
                        <a href="{{ url_for('manager.logs') }}" class="navbar-brand nav-link text-success rounded p-2"
                            id="side_logs">
                            <i class="bi bi-clock-history"></i>
                            <span class="ps-1 fs-5 d-none d-sm-inline">Activities</span>
                        </a>
                    </li>

                    <li class="nav-item mb-2">
                        <a href="{{ url_for('public.logout') }}" class="navbar-brand nav-link text-danger rounded p-2">
                            <i class="bi bi-escape"></i>
                            <span class="ps-1 fs-5 d-none d-sm-inline">Logout</span>
                        </a>
                    </li>
                </ul>
            </div>
        </aside>

        <div class="container-fluid">
            <!-- Notice section start -->
            <div class="clearfix mt-2">
                <div class="mx-auto" style="max-width: 500px;">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                    {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible text-center fw-bold mb-2" fade show>
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                        {{ message }}
                    </div>
                    {% endfor %}
                    {% endif %}
                    {% endwith %}
                </div>
            </div>
            <!-- Notice section end -->

            {% block content %}
            {% endblock content %}
        </div>
    </main>
    <!-- JS -->
    <script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.bundle.min.js')}}"></script>
</body>

</html>

src/templates/layout/layout_patient.html
{% block content %}
    
{% endblock content %}
    

src/templates/layout/layout_public.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" , shrink-to-fit="no">
    {% if title %}
    <title>MediPlus - {{ title }}</title>
    {% else %}
    <title>MediPlus</title>
    {% endif %}

    <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='32' height='32' fill='%23198754' viewBox='0 0 16 16'%3E%3Cpath
    d='M1.475 9C2.702 10.84 4.779 12.871 8 15c3.221-2.129 5.298-4.16 6.525-6H12a.5.5 0 0 1-.464-.314l-1.457-3.642-1.598
    5.593a.5.5 0 0 1-.945.049L5.889 6.568l-1.473 2.21A.5.5 0 0 1 4 9z'/%3E%3Cpath d='M.88 8C-2.427 1.68 4.41-2 7.823
    1.143q.09.083.176.171a3 3 0 0 1 .176-.17C11.59-2 18.426 1.68 15.12 8h-2.783l-1.874-4.686a.5.5 0 0 0-.945.049L7.921 8.956
    6.464 5.314a.5.5 0 0 0-.88-.091L3.732 8z'/%3E%3C/svg%3E" />

    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap-icons.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='mycss/color.css')}}">
    <!-- JS -->
    <script type="text/javascript" src="{{url_for('static', filename='js/jquery-3.7.1.min.js') }}"></script>
</head>

<body id="body" class="d-flex flex-column min-vh-100 bg-light-subtle">
    <header style="padding-bottom: 3.5em;">
        <nav class="navbar navbar-expand-md fixed-top bg-lightmint">
            <div class="container">
                <a class="navbar-brand fs-5" href="{{ url_for('public.index')}}">
                    <i class="bi bi-heart-pulse-fill text-success"></i>
                    <b class="text-danger">Medi</b><b class="text-success">Plus</b>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                        {% if current_user.is_authenticated %}
                            {% if current_user.role == "Patient" %}
                                {% if session['pending_items'] > 0 %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('patient.pending_items') }}">
                                        Pending Items
                                        <small>
                                            <sup class="badge rounded-pill text-bg-danger">{{ session['pending_items'] }}</sup>
                                        </small>
                                    </a>
                                </li>
                                {% endif %}
                            {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('public.dashboard') }}">
                                Dashboard
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="{{ url_for('public.logout') }}">
                                Logout
                            </a>
                        </li>

                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('public.doctors') }}">
                                Doctors
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('public.tests') }}">
                                Tests
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('public.login') }}">
                                Login
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('public.register') }}">
                                Register
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!-- Notice section start -->
    <div class="clearfix mt-3 ms-2 me-2">
        <div class="mx-auto" style="max-width: 500px;">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible text-center mb-2 fw-bold" fade show>
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </div>
    <!-- Notice section end -->

    {% block content %}
    {% endblock content %}

    <footer class="mt-auto pt-2" style="background-color: #d6f6d4;">
        <p class="text-center text-muted">
            © MediPlus 2024, <a class="text-primary text-decoration-none" href="{{ url_for('public.about') }}" target="_blank">About This Project</a>
        </p>
    </footer>

    <!-- JS -->
    <script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.bundle.min.js')}}"></script>
</body>

</html>