src/doctor/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import (
    SelectField,
    SubmitField,
    DateField,
    PasswordField,
    StringField,
    DecimalField,
    TextAreaField,
    SelectMultipleField,
)
from wtforms.validators import DataRequired, EqualTo, Length
from datetime import date


class UpdateProfileForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    first_name = StringField("First Name", validators=[DataRequired()])
    last_name = StringField("Last Name", validators=[DataRequired()])
    gender = SelectField(
        "Gender",
        validators=[DataRequired()],
        choices=[("Male", "Male"), ("Female", "Female")],
    )
    birthdate = DateField("Birth Date", validators=[DataRequired()], default=date.today)
    phone = StringField("Phone", validators=[DataRequired()])
    email = StringField("Email Address", validators=[DataRequired()])
    avatar = FileField(
        "Change Avatar",
        validators=[
            FileAllowed(["jpg", "jpeg", "png", "svg"], "Please pick correct format!")
        ],
    )

    submit = SubmitField("Update Profile")


class ChangePasswordForm(FlaskForm):
    current_password = PasswordField("Current Password", validators=[DataRequired()])
    new_password = PasswordField(
        "New Password",
        validators=[
            DataRequired(),
            EqualTo("confirm_password", "Password didn't match!"),
        ],
    )
    confirm_password = PasswordField("Confirm Password", validators=[DataRequired()])

    submit = SubmitField("Change Password")


class UpdateScheduleForm(FlaskForm):
    days = SelectMultipleField(
        "Select Available Days",
        validators=[DataRequired()],
        choices=[
            (6, "Saturday"),
            (0, "Sunday"),
            (1, "Monday"),
            (2, "Tuesday"),
            (3, "Wednesday"),
            (4, "Thursday"),
            (5, "Friday"),
        ],
    )
    times = SelectMultipleField(
        "Select Time Slot",
        choices=[
            ("00-01", "00-01"),
            ("01-02", "01-02"),
            ("02-03", "02-03"),
            ("03-04", "03-04"),
            ("04-05", "04-05"),
            ("05-06", "05-06"),
            ("06-07", "06-07"),
            ("07-08", "07-08"),
            ("08-09", "08-09"),
            ("09-10", "09-10"),
            ("10-11", "10-11"),
            ("11-12", "11-12"),
            ("12-13", "12-13"),
            ("13-14", "13-14"),
            ("14-15", "14-15"),
            ("15-16", "15-16"),
            ("16-17", "16-17"),
            ("17-18", "17-18"),
            ("18-19", "18-19"),
            ("19-20", "19-20"),
            ("20-21", "20-21"),
            ("21-22", "21-22"),
            ("22-23", "22-23"),
            ("23-00", "23-00"),
        ],
    )
    submit = SubmitField("Update Schedule")


class PresItemForm(FlaskForm):
    item_medicine = StringField("Medicine", validators=[DataRequired()])
    item_dosage = StringField("Dosage", validators=[DataRequired()])
    item_duration = StringField("Duration", validators=[DataRequired()])
    item_instruction = StringField("Instruction", validators=[DataRequired()])
    item_submit = SubmitField("Add to Prescription")

class PresEditItemForm(FlaskForm):
    edit_medicine = StringField("Medicine", validators=[DataRequired()])
    edit_dosage = StringField("Dosage", validators=[DataRequired()])
    edit_duration = StringField("Duration", validators=[DataRequired()])
    edit_instruction = StringField("Instruction", validators=[DataRequired()])
    edit_submit = SubmitField("Update")

src/patient/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import (
    SelectField,
    SubmitField,
    DateField,
    PasswordField,
    StringField,
    DecimalField,
)
from wtforms.validators import DataRequired, EqualTo
from datetime import date


class ChangePasswordForm(FlaskForm):
    current_password = PasswordField("Current Password", validators=[DataRequired()])
    new_password = PasswordField("New Password", validators=[DataRequired()])
    confirm_password = PasswordField(
        "Confirm Password", validators=[DataRequired(), EqualTo("new_password")]
    )

    submit = SubmitField("Change Password")


class UpdateProfileForm(FlaskForm):
    first_name = StringField("First Name", validators=[DataRequired()])
    last_name = StringField("Last Name", validators=[DataRequired()])
    gender = SelectField(
        "Gender",
        validators=[DataRequired()],
        choices=[("Male", "Male"), ("Female", "Female")],
    )
    birthdate = DateField("Birth Date", validators=[DataRequired()])
    email = StringField("Email Address", validators=[DataRequired()])
    phone = StringField("Phone Number", validators=[DataRequired()])
    avatar = FileField(
        "Update Display Picture",
        validators=[
            FileAllowed(["jpg", "jpeg", "png", "svg"], "Please pick correct format!")
        ],
    )

    submit = SubmitField("Update Profile")


class MedicalInfoForm(FlaskForm):
    blood_group = StringField("Blood Group", validators=[DataRequired()])
    height_cm = DecimalField("Height(CM)")
    weight_kg = DecimalField("Weight(KG)")
    allergies = StringField("Allergies")
    medical_conditions = StringField("Medical Conditions")
    submit = SubmitField("Update Information")


class Record_Upload_Form(FlaskForm):
    file_name = StringField("File Name", validators=[DataRequired()])
    file = FileField(
        "Pick a Record File",
        validators=[
            DataRequired(),
            FileAllowed(
                ["jpg", "jpeg", "png", "svg", "pdf"], "Please pick allowed format!"
            ),
        ],
    )
    submit = SubmitField("Upload New Record")

src/manager/__init__.py
2

src/manager/routes.py
import os
import json
import secrets
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    flash,
    request,
    session,
    abort,
    current_app,
    send_file,
)
from flask_login import login_required, current_user
from sqlalchemy.orm import aliased
from src.users.models import Users, User_Logs, Patients, Doctors, Managers
from src.doctor.models import (
    Doctor_Time,
    Appointments,
    Appointment_Details,
)
from src.patient.models import (
    Invoices,
    Invoice_Items,
    Payments,
    Medical_Info,
    Medical_Tests,
    Medical_Test_Book,
    Medical_Report_Files,
    Patient_Record_Files,
)
from src.doctor.forms import UpdateScheduleForm
from src.manager.forms import (
    LogSortForm,
    ChangePasswordForm,
    SelfProfileForm,
    NewMedicalTestForm,
    UpdateMedicalTestForm,
    UpdateInvoiceForm,
    Test_Result_Upload_Form,
    RegisterDoctorForm,
    UpdateDoctorForm,
    DoctorPasswordForm,
    ManagerPasswordForm,
    RegisterManagerForm,
    SearchInvoiceForm,
    SearchTestbookForm,
    SearchAppointmentForm,
)
from src.public.forms import SearchTestForm, SearchDoctorForm
from src import db, hash_manager
from src.public.utils import (
    get_datetime,
    profile_picture_saver,
    profile_picture_remover,
)
from src.manager.utils import users_pie_data, user_logs_bar_data


# Declare Blueprint
manager = Blueprint("manager", __name__)


@manager.route("/dashboard/manager")
@login_required
def dashboard():
    if current_user.role != "Manager":
        abort(403)

    counts = {
        "patients": Users.query.filter(Users.role == "Patient").count(),
        "managers": Users.query.filter(Users.role == "Manager").count(),
        "doctors": Users.query.filter(Users.role == "Doctor").count(),
        "tests": Medical_Test_Book.query.filter(
            Medical_Test_Book.test_status == "Done"
        ).count(),
        "appt": Appointment_Details.query.filter(
            Appointment_Details.appt_status == "Completed"
        ).count(),
        "invoices": Invoices.query.count(),
    }

    pie_data = users_pie_data()
    bar_data = user_logs_bar_data(days=7)

    return render_template(
        "manager/dashboard.html",
        counts=counts,
        pie_data=json.dumps(pie_data),
        bar_data=json.dumps(bar_data),
        title="Manager Dashboard",
    )


@manager.route("/dashboard/manager/appointments", methods=["GET", "POST"])
@login_required
def appointments():
    if current_user.role != "Manager":
        abort(403)

    page_num = request.args.get("page", 1, int)
    title = "Appointments List"
    search = "no"

    form = SearchAppointmentForm()

    doctors = aliased(Doctors)
    patients = aliased(Patients)

    appointments = (
        Appointments.query.join(
            Appointment_Details, Appointments.appt_id == Appointment_Details.appt_id
        )
        .join(doctors, Appointments.appt_doctor_id == doctors.d_id)
        .join(patients, Appointments.appt_patient_id == patients.p_id)
        .order_by(Appointments.appt_id.desc())
        .add_columns(
            Appointments.appt_id,
            Appointment_Details.appt_status,
            Appointment_Details.appt_date,
            Appointment_Details.appt_time,
            doctors.d_id.label("doctor_id"),
            doctors.last_name.label("doctor_last_name"),
            doctors.first_name.label("doctor_first_name"),
            patients.p_id.label("patient_id"),
            patients.last_name.label("patient_last_name"),
            patients.first_name.label("patient_first_name"),
        )
        .paginate(page=page_num, per_page=15)
    )

    if form.validate_on_submit():
        if page_num > 1:
            page_num = 1
        search = "yes"
        title = f"Search Result: {form.keyword.data}"

        if form.search_by.data == "patient_name":
            appointments = (
                Appointments.query.join(
                    Appointment_Details,
                    Appointments.appt_id == Appointment_Details.appt_id,
                )
                .join(doctors, Appointments.appt_doctor_id == doctors.d_id)
                .join(patients, Appointments.appt_patient_id == patients.p_id)
                .filter(
                    patients.last_name.icontains(form.keyword.data)
                    | patients.first_name.icontains(form.keyword.data)
                )
                .order_by(Appointments.appt_id.desc())
                .add_columns(
                    Appointments.appt_id,
                    Appointment_Details.appt_status,
                    Appointment_Details.appt_date,
                    Appointment_Details.appt_time,
                    doctors.d_id.label("doctor_id"),
                    doctors.last_name.label("doctor_last_name"),
                    doctors.first_name.label("doctor_first_name"),
                    patients.p_id.label("patient_id"),
                    patients.last_name.label("patient_last_name"),
                    patients.first_name.label("patient_first_name"),
                )
                .paginate(page=page_num, per_page=15)
            )
        elif form.search_by.data == "doctor_name":
            appointments = (
                Appointments.query.join(
                    Appointment_Details,
                    Appointments.appt_id == Appointment_Details.appt_id,
                )
                .join(doctors, Appointments.appt_doctor_id == doctors.d_id)
                .join(patients, Appointments.appt_patient_id == patients.p_id)
                .filter(
                    doctors.last_name.icontains(form.keyword.data)
                    | doctors.first_name.icontains(form.keyword.data)
                )
                .order_by(Appointments.appt_id.desc())
                .add_columns(
                    Appointments.appt_id,
                    Appointment_Details.appt_status,
                    Appointment_Details.appt_date,
                    Appointment_Details.appt_time,
                    doctors.d_id.label("doctor_id"),
                    doctors.last_name.label("doctor_last_name"),
                    doctors.first_name.label("doctor_first_name"),
                    patients.p_id.label("patient_id"),
                    patients.last_name.label("patient_last_name"),
                    patients.first_name.label("patient_first_name"),
                )
                .paginate(page=page_num, per_page=15)
            )
        elif form.search_by.data == "date":
            appointments = (
                Appointments.query.join(
                    Appointment_Details,
                    Appointments.appt_id == Appointment_Details.appt_id,
                )
                .join(doctors, Appointments.appt_doctor_id == doctors.d_id)
                .join(patients, Appointments.appt_patient_id == patients.p_id)
                .filter(Appointment_Details.appt_date == form.keyword.data)
                .order_by(Appointments.appt_id.desc())
                .add_columns(
                    Appointments.appt_id,
                    Appointment_Details.appt_status,
                    Appointment_Details.appt_date,
                    Appointment_Details.appt_time,
                    doctors.d_id.label("doctor_id"),
                    doctors.last_name.label("doctor_last_name"),
                    doctors.first_name.label("doctor_first_name"),
                    patients.p_id.label("patient_id"),
                    patients.last_name.label("patient_last_name"),
                    patients.first_name.label("patient_first_name"),
                )
                .paginate(page=page_num, per_page=15)
            )

    return render_template(
        "manager/appointments.html",
        appointments=appointments,
        form=form,
        search=search,
        title=title,
    )


@manager.route("/dashboard/manager/appointments/<appt_id>/cancel")
@login_required
def cancel_appointment(appt_id):
    if current_user.role != "Manager":
        abort(403)

    appointment_details: Appointment_Details = Appointment_Details.query.filter(
        Appointment_Details.appt_id == int(appt_id)
    ).first_or_404()
    appointment_details.appt_status = "Cancelled"
    appointment: Appointments = Appointments.query.filter(
        Appointments.appt_id == int(appt_id)
    ).first()

    date, time = get_datetime()
    manager_log: User_Logs = User_Logs(
        current_user.id, "Cancel Appointment", date, time
    )
    manager_log.log_desc = f"Appointment #{appointment.appt_id}, Patient #{appointment.appt_patient_id} on {appointment_details.appt_date} ({appointment_details.appt_time})"
    db.session.add(manager_log)

    patient_log: User_Logs = User_Logs(
        appointment.appt_patient_id, "Appointment Cancelled", date, time
    )
    patient_log.log_desc = (
        f"Doctor has cancelled your appointment. Try different date/time slot."
    )
    db.session.add(patient_log)

    db.session.commit()

    flash("Appointment has been cancelled!", category="warning")
    return redirect(url_for("manager.appointments"))


@manager.route("/dashboard/manager/tests", methods=["GET", "POST"])
@login_required
def tests():
    if current_user.role != "Manager":
        abort(403)

    page_num = request.args.get("page", 1, int)
    title = "Medical Tests Booking"
    search = "no"

    form = SearchTestbookForm()

    items = (
        Medical_Test_Book.query.join(
            Invoice_Items,
            Invoice_Items.item_id == Medical_Test_Book.invoice_item_id,
        )
        .order_by(Medical_Test_Book.serial_number.desc())
        .join(Invoices, Invoice_Items.invoice_id == Invoices.invoice_id)
        .join(Patients, Patients.p_id == Invoices.invoice_patient_id)
        .join(Users, Users.id == Patients.p_id)
        .add_columns(
            Medical_Test_Book.serial_number,
            Medical_Test_Book.invoice_item_id,
            Medical_Test_Book.test_status,

src/templates/manager/dashboard.html
{% extends 'layout/layout_manager.html' %}


{% block content %}
<!-- <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js"></script> -->
<div class="container-fluid">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb breadcrumb-chevron p-3 bg-body-tertiary rounded-3">
            <li class="breadcrumb-item">
                <a class="link-body-emphasis fw-semibold text-decoration-none" href="{{ url_for('public.index') }}">
                    <i class="bi bi-house-door-fill"></i> Home
                </a>
            </li>
            <li class="breadcrumb-item">
                <a class="link-body-emphasis fw-semibold text-decoration-none" href="{{ url_for('public.dashboard') }}">
                    Dashboard
                </a>
            </li>
            <li class="breadcrumb-item active">
                Overview
            </li>
        </ol>
    </nav>
</div>

<div class="container">
    <div class="row gy-3">
        <div class="col-md-2 mb-2 pop">
            <a href="{{ url_for('manager.patients') }}" class="text-decoration-none">
                <div class="card h-100 bg-danger-subtle text-danger">
                    <div class="card-body text-center">
                        <h5 class="card-title fs-3 fw-bold">
                            {{ counts["patients"]}}
                        </h5>
                        <p class="card-text">
                            Registered Patients
                        </p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-2 mb-2 pop">
            <a href="{{ url_for('manager.doctors') }}" class="text-decoration-none">
                <div class="card h-100 bg-success-subtle text-success">
                    <div class="card-body text-center">
                        <h5 class="card-title fs-3 fw-bold">
                            {{ counts["doctors"]}}
                        </h5>
                        <p class="card-text">
                            Registered Doctors
                        </p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-2 mb-2 pop">
            <a href="{{ url_for('manager.managers') }}" class="text-decoration-none">
                <div class="card h-100 bg-info-subtle text-info">
                    <div class="card-body text-center">
                        <h5 class="card-title fs-3 fw-bold">
                            {{ counts["managers"]}}
                        </h5>
                        <p class="card-text">
                            Working Managers
                        </p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-2 mb-2 pop">
            <a href="{{ url_for('manager.tests') }}" class="text-decoration-none">
                <div class="card h-100 bg-primary-subtle text-primary">
                    <div class="card-body text-center">
                        <h5 class="card-title fs-3 fw-bold">
                            {{ counts["tests"]}}
                        </h5>
                        <p class="card-text">
                            Medical Tests Done
                        </p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-2 mb-2 pop">
            <a href="{{ url_for('manager.appointments') }}" class="text-decoration-none">
                <div class="card h-100 bg-warning-subtle text-warning">
                    <div class="card-body text-center">
                        <h5 class="card-title fs-3 fw-bold">
                            {{ counts["appt"]}}
                        </h5>
                        <p class="card-text">
                            Doctor Meetup
                        </p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-2 mb-2 pop">
            <a href="{{ url_for('manager.invoices') }}" class="text-decoration-none">
                <div class="card h-100 bg-dark-subtle text-dark">
                    <div class="card-body text-center">
                        <h5 class="card-title fs-3 fw-bold">
                            {{ counts["invoices"]}}
                        </h5>
                        <p class="card-text">
                            Completed Invoices
                        </p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

<div class="container overflow-hidden text-center mt-3">
    <div class="ms-1 row border rounded-3">
        <div class="col-md-4">
            <div id="pie_pat"></div>
        </div>
        <div class="col-md-4">
            <div id="pie_doc"></div>
        </div>
        <div class="col-md-4">
            <div id="pie_man"></div>
        </div>
    </div>
</div>
<div class="container overflow-hidden text-center mt-1">
    <div class="border rounded-3">
        <div id="bar_chart"></div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#side_overview").addClass("text-success-emphasis bg-success-subtle");
    });
    // Convert data
    const pie_data = JSON.parse('{{ pie_data | safe }}');
    const bar_data = JSON.parse('{{ bar_data | safe }}')
    
    // Pie charts
    Plotly.newPlot("pie_pat", pie_data["pat"], { title: "Patients" }, { responsive: true });
    Plotly.newPlot("pie_doc", pie_data["doc"], { title: "Doctors" }, { responsive: true });
    Plotly.newPlot("pie_man", pie_data["man"], { title: "Managers" }, { responsive: true });

    // Bar chart
    const xArray = [55, 49, 44, 24, 15];
    const yArray = ["Italy", "France", "Spain", "USA", "Argentina"];

    Plotly.newPlot("bar_chart", bar_data, { title: "User Activities(Last 7 Days)" }, { responsive: true });
</script>
{% endblock content %}

src/templates/manager/tests.html
{% extends 'layout/layout_manager.html' %}


{% block content %}
<div class="container-fluid">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb breadcrumb-chevron p-3 bg-body-tertiary rounded-3">
            <li class="breadcrumb-item">
                <a class="link-body-emphasis fw-semibold text-decoration-none" href="{{ url_for('public.index') }}">
                    <i class="bi bi-house-door-fill"></i> Home
                </a>
            </li>
            <li class="breadcrumb-item">
                <a class="link-body-emphasis fw-semibold text-decoration-none" href="{{ url_for('public.dashboard') }}">
                    Dashboard
                </a>
            </li>
            <li class="breadcrumb-item active">
                Medical Tests
            </li>
        </ol>
    </nav>
</div>
<div class="container mt-3">
    <div class="text-end">
        <a href="{{ url_for('manager.test_catalog') }}"
            class="btn btn-primary text-white fw-bold pop">
            <i class="bi bi-card-list"></i> Test Catalog
        </a>
    </div>
</div>
<!-- Filter -->
<div class="container mt-3 mb-3">
    <div class="border rounded mb-3 p-3">
        <h4 class="fs-5 mb-2">
            <i class="bi bi-search"></i> Search Tests
        </h4>
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <div class="row">
                <div class="col">
                    {{ form.search_by.label(class='form-label') }}
                    {{ form.search_by(class='form-select') }}
                </div>
                <div class="col">
                    {{ form.keyword.label(class='form-label') }}
                    {{ form.keyword(class='form-control', placeholder='Type Patient Name/Test Date/Serial Number') }}
                    {% if form.keyword.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.keyword.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
                <div class="col mt-auto">
                    {{ form.submit(class='btn btn-primary rounded-3 text-white fw-bold pop') }}
                </div>
            </div>
        </form>
        {% if search == "yes" %}
        <div class="text-center fw-bold mt-2">
            <a href="{{ url_for('manager.tests') }}">Show All</a>
        </div>
        {% endif %}
    </div>
</div>
{% if items.total > 0 %}
<!-- Tests -->
<div class="container mt-3">
    <div class="fs-4 fw-semibold mb-3">
        Test Booking List ({{ items.total }})
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-responsive">
            <thead class="table-primary">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Description</th>
                    <th scope="col">Status</th>
                    <th scope="col">Invoice</th>
                    <th scope="col">Patient</th>
                    <th scope="col">Invoice Date</th>
                    <th scope="col" class="text-end">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                <tr>
                    <th scope="row">{{ item.serial_number }}</th>
                    <td>{{ item.item_desc }}</td>
                    <td>
                        {% if item.test_status == "Pending" %}
                        <span class="text-danger spinner-border spinner-border-sm" aria-hidden="true"></span>
                        <span class="visually-hidden" role="status">Pending...</span>
                        {% else %}
                        <i class="text-success bi bi-check-circle-fill"></i>
                        {% endif %}
                    </td>
                    <td>
                        {% if item.status == "Unpaid" %}
                        <span class="text-danger">{{ item.status }}</span>
                        {% else %}
                        <span class="text-success">{{ item.status }}</span>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ url_for('manager.view_patient', id=item.p_id)}}"
                            class="text-decoration-none" target="_blank">
                            {{ item.last_name }} {{ item.first_name }}
                        </a>
                        {% if item.gender == "Male" %}
                        <span class="badge bg-info-subtle text-info-emphasis rounded-pill">
                            <i class="bi bi-gender-male"></i>
                        </span>
                        {% else %}
                        <span class="badge bg-warning-subtle text-warning-emphasis rounded-pill">
                            <i class="bi bi-gender-female"></i>
                        </span>
                        {% endif %}
                    </td>
                    <td>{{ item.invoice_date}}</td>
                    <td class="text-end">
                        <a href="{{ url_for('manager.invoice_update', id=item.invoice_id)}}"
                            class="btn btn-sm btn-secondary text-white pop">
                            Invoice
                        </a>
                        <a href="{{ url_for('manager.test_details', serial_number=item.serial_number)}}"
                            class="btn btn-sm btn-success text-white pop">
                            Update
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<!-- Pagination -->
<div class="container mt-3 mb-3">
    <div class="d-flex justify-content-center border rounded">
        {% for page_num in items.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
        {% if items.page == page_num %}
        <a class="btn btn-sm btn-primary m-2 pop" href="{{ url_for('manager.tests', page=page_num) }}"
            id="pg_link{{ page_num }}">
            {{ page_num }}
        </a>
        {% else %}
        <a class="btn btn-sm btn-outline-primary m-2 pop" href="{{ url_for('manager.tests', page=page_num) }}"
            id="pg_link{{ page_num }}">
            {{ page_num }}
        </a>
        {% endif %}
        {% else %}
        <button class="btn btn-sm btn-outline-secondary m-2" disabled>
            ...
        </button>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% else %}
<div class="container mt-3">
    <div class="alert alert-warning alert-dismissible fade show fw-light" role="alert">
        <i class="bi bi-info-circle-fill"></i> Sorry, no results found!
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
</div>
{% endif %}
    
<!-- JS -->
<script>
    $(document).ready(function () {
        $("#side_tests").addClass("text-success-emphasis bg-success-subtle");
    });
</script>
{% endblock content %}