src/doctor/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import (
    SelectField,
    SubmitField,
    DateField,
    PasswordField,
    StringField,
    DecimalField,
    TextAreaField,
    SelectMultipleField,
)
from wtforms.validators import DataRequired, EqualTo, Length
from datetime import date


class UpdateProfileForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    first_name = StringField("First Name", validators=[DataRequired()])
    last_name = StringField("Last Name", validators=[DataRequired()])
    gender = SelectField(
        "Gender",
        validators=[DataRequired()],
        choices=[("Male", "Male"), ("Female", "Female")],
    )
    birthdate = DateField("Birth Date", validators=[DataRequired()], default=date.today)
    phone = StringField("Phone", validators=[DataRequired()])
    email = StringField("Email Address", validators=[DataRequired()])
    avatar = FileField(
        "Change Avatar",
        validators=[
            FileAllowed(["jpg", "jpeg", "png", "svg"], "Please pick correct format!")
        ],
    )

    submit = SubmitField("Update Profile")


class ChangePasswordForm(FlaskForm):
    current_password = PasswordField("Current Password", validators=[DataRequired()])
    new_password = PasswordField(
        "New Password",
        validators=[
            DataRequired(),
            EqualTo("confirm_password", "Password didn't match!"),
        ],
    )
    confirm_password = PasswordField("Confirm Password", validators=[DataRequired()])

    submit = SubmitField("Change Password")


class UpdateScheduleForm(FlaskForm):
    days = SelectMultipleField(
        "Select Available Days",
        validators=[DataRequired()],
        choices=[
            (6, "Saturday"),
            (0, "Sunday"),
            (1, "Monday"),
            (2, "Tuesday"),
            (3, "Wednesday"),
            (4, "Thursday"),
            (5, "Friday"),
        ],
    )
    times = SelectMultipleField(
        "Select Time Slot",
        choices=[
            ("00-01", "00-01"),
            ("01-02", "01-02"),
            ("02-03", "02-03"),
            ("03-04", "03-04"),
            ("04-05", "04-05"),
            ("05-06", "05-06"),
            ("06-07", "06-07"),
            ("07-08", "07-08"),
            ("08-09", "08-09"),
            ("09-10", "09-10"),
            ("10-11", "10-11"),
            ("11-12", "11-12"),
            ("12-13", "12-13"),
            ("13-14", "13-14"),
            ("14-15", "14-15"),
            ("15-16", "15-16"),
            ("16-17", "16-17"),
            ("17-18", "17-18"),
            ("18-19", "18-19"),
            ("19-20", "19-20"),
            ("20-21", "20-21"),
            ("21-22", "21-22"),
            ("22-23", "22-23"),
            ("23-00", "23-00"),
        ],
    )
    submit = SubmitField("Update Schedule")


class PresItemForm(FlaskForm):
    item_medicine = StringField("Medicine", validators=[DataRequired()])
    item_dosage = StringField("Dosage", validators=[DataRequired()])
    item_duration = StringField("Duration", validators=[DataRequired()])
    item_instruction = StringField("Instruction", validators=[DataRequired()])
    item_submit = SubmitField("Add to Prescription")

class PresEditItemForm(FlaskForm):
    edit_medicine = StringField("Medicine", validators=[DataRequired()])
    edit_dosage = StringField("Dosage", validators=[DataRequired()])
    edit_duration = StringField("Duration", validators=[DataRequired()])
    edit_instruction = StringField("Instruction", validators=[DataRequired()])
    edit_submit = SubmitField("Update")

src/doctor/routes.py
import os
from src import db, hash_manager
from src.public.utils import (
    get_datetime,
    profile_picture_remover,
    profile_picture_saver,
)
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    flash,
    abort,
    request,
    jsonify,
    current_app,
    send_file,
)
from flask_login import login_required, current_user
from src.users.models import Users, User_Logs, Doctors, Patients, Managers
from src.patient.models import (
    Medical_Info,
    Medical_Report_Files,
    Medical_Test_Book,
    Invoices,
    Invoice_Items,
    Patient_Record_Files,
)
from src.doctor.models import Doctor_Time
from src.doctor.models import (
    Appointments,
    Appointment_Details,
    Prescriptions,
    Prescription_Extras,
    Prescribed_Items,
)
from src.doctor.forms import (
    UpdateProfileForm,
    ChangePasswordForm,
    UpdateScheduleForm,
    PresItemForm,
    PresEditItemForm,
)


doctor = Blueprint("doctor", __name__)


@doctor.route("/dashboard/doctor")
@login_required
def dashboard():
    if current_user.role != "Doctor":
        abort(403)

    user = (
        Doctors.query.filter(Doctors.d_id == current_user.id)
        .join(Users, Doctors.d_id == Users.id)
        .join(Doctor_Time, Doctor_Time.doctor_id == Doctors.d_id)
        .add_columns(
            Users.username,
            Users.gender,
            Users.email,
            Doctors.title,
            Doctors.first_name,
            Doctors.last_name,
            Doctors.phone,
            Doctors.birthdate,
            Doctors.avatar,
            Doctor_Time.appt_status,
        )
        .first()
    )

    pending_count = (
        Appointments.query.filter(Appointments.appt_doctor_id == current_user.id)
        .join(Appointment_Details, Appointment_Details.appt_id == Appointments.appt_id)
        .filter(Appointment_Details.appt_status == "Booked")
        .count()
    )

    ip = request.remote_addr
    info = request.headers.get("User-Agent")

    return render_template(
        "doctor/dashboard.html",
        user=user,
        pending=pending_count,
        ip=ip,
        info=info,
        title="Dashboard",
    )


@doctor.route("/dashboard/doctor/change_status")
@login_required
def change_appt_status():
    if current_user.role != "Doctor":
        abort(403)

    doctor_time: Doctor_Time = Doctor_Time.query.filter(
        Doctor_Time.doctor_id == current_user.id
    ).first_or_404()

    if doctor_time.appt_status == "Available":
        doctor_time.appt_status = "Unavailable"
    else:
        doctor_time.appt_status = "Available"

    date, time = get_datetime()
    new_log = User_Logs(current_user.id, "Change Status", date, time)
    db.session.add(new_log)
    db.session.commit()

    flash("Status Changed Successfully!", category="success")
    return redirect(url_for("doctor.dashboard"))


@doctor.route("/dashboard/doctor/patients")
@login_required
def patients():
    if current_user.role != "Doctor":
        abort(403)

    page_num = request.args.get("page", 1, int)

    patients = (
        Patients.query.join(Appointments, Appointments.appt_patient_id == Patients.p_id)
        .filter(Appointments.appt_doctor_id == current_user.id)
        .join(Appointment_Details, Appointment_Details.appt_id == Appointments.appt_id)
        .filter(Appointment_Details.appt_status == "Completed")
        .join(Users, Users.id == Patients.p_id)
        .add_columns(
            Patients.p_id,
            Patients.last_name,
            Patients.first_name,
            Patients.phone,
            Patients.birthdate,
            Patients.avatar,
            Users.gender,
        )
        .paginate(page=page_num, per_page=12)
    )
    return render_template(
        "doctor/patients.html", patients=patients, title="My Patients"
    )


@doctor.route("/dashboard/doctor/patients/<patient_id>")
@login_required
def view_patient(patient_id):
    if current_user.role != "Doctor":
        abort(403)

    page_num = request.args.get("page", 1, int)

    patient: Patients = (
        Patients.query.filter(Patients.p_id == int(patient_id))
        .join(Users, Users.id == Patients.p_id)
        .join(Medical_Info, Medical_Info.patient_id == Patients.p_id)
        .add_columns(
            Patients.p_id,
            Patients.last_name,
            Patients.first_name,
            Patients.phone,
            Patients.birthdate,
            Patients.avatar,
            Users.gender,
            Users.email,
            Medical_Info.blood_group,
            Medical_Info.height_cm,
            Medical_Info.weight_kg,
            Medical_Info.allergies,
            Medical_Info.medical_conditions,
        )
        .first_or_404()
    )

    files: Patient_Record_Files = (
        Patient_Record_Files.query.filter(
            Patient_Record_Files.record_patient_id == int(patient_id)
        )
        .order_by(Patient_Record_Files.file_id.desc())
        .paginate(page=page_num, per_page=10)
    )

    return render_template(
        "doctor/view_patient.html",
        patient=patient,
        files=files,
        title=f"Patient {patient.last_name} {patient.first_name}",
    )


@doctor.route("/dashboard/doctor/patients/<patient_id>/appointments")
@login_required
def view_patient_appointments(patient_id):
    if current_user.role != "Doctor":
        abort(403)

    page_num = request.args.get("page", 1, int)

    patient: Patients = Patients.query.filter(
        Patients.p_id == int(patient_id)
    ).first_or_404()
    appointments = (
        Appointments.query.filter(Appointments.appt_patient_id == patient.p_id)
        .join(Appointment_Details, Appointment_Details.appt_id == Appointments.appt_id)
        .filter(Appointment_Details.appt_status == "Completed")
        .join(Doctors, Appointments.appt_doctor_id == Doctors.d_id)
        .join(Users, Users.id == Doctors.d_id)
        .order_by(Appointment_Details.appt_date.desc())
        .add_columns(
            Appointments.appt_id,
            Appointment_Details.appt_status,
            Appointment_Details.appt_date,
            Appointment_Details.appt_time,
            Doctors.d_id,
            Doctors.last_name,
            Doctors.first_name,
            Doctors.title,
            Doctors.avatar,
            Users.gender,
        )
        .paginate(page=page_num, per_page=10)
    )

    return render_template(
        "doctor/patient_appointments.html",
        patient=patient,
        appointments=appointments,
        title=f"Patient Appointment History",
    )


@doctor.route("/dashboard/doctor/patients/<patient_id>/tests")
@login_required
def view_patient_tests(patient_id):
    if current_user.role != "Doctor":
        abort(403)

    page_num = request.args.get("page", 1, int)

    patient: Patients = Patients.query.filter(
        Patients.p_id == int(patient_id)
    ).first_or_404()
    tests = (
        Medical_Test_Book.query.filter(
            Medical_Test_Book.test_patient_id == Patients.p_id
        )
        .filter(Medical_Test_Book.test_patient_id == patient.p_id)
        .filter(Medical_Test_Book.test_status == "Done")
        .join(Invoice_Items, Invoice_Items.item_id == Medical_Test_Book.invoice_item_id)
        .join(Invoices, Invoices.invoice_id == Invoice_Items.invoice_id)
        .order_by(Invoices.invoice_date.desc())
        .add_columns(
            Medical_Test_Book.serial_number,
            Invoice_Items.item_desc,
            Invoices.invoice_date,
        )
        .paginate(page=page_num, per_page=12)
    )

    return render_template(
        "doctor/patient_test_history.html",
        patient=patient,
        tests=tests,
        title=f"Patient Medical Tests",
    )


@doctor.route("/dashboard/doctor/patients/<patient_id>/test_file/<file_id>")
@login_required
def view_patient_test_file(patient_id, file_id):
    if current_user.role != "Doctor":
        abort(403)

    patient = Patients.query.filter(Patients.p_id == int(patient_id)).first_or_404()
    file = (
        Medical_Report_Files.query.filter(Medical_Report_Files.file_id == int(file_id))
        .join(
            Medical_Test_Book,
            Medical_Report_Files.test_book_serial == Medical_Test_Book.serial_number,
        )
        .join(Managers, Medical_Report_Files.upload_manager_id == Managers.m_id)
        .add_columns(
            Medical_Report_Files.file_id,
            Medical_Report_Files.file_name,
            Medical_Report_Files.file_path_name,
            Medical_Report_Files.file_size_kb,
            Medical_Report_Files.upload_date,
            Medical_Report_Files.upload_time,
            Medical_Report_Files.test_book_serial,
            Managers.first_name,
            Managers.last_name,
        )
        .first_or_404()
    )

    return render_template(
        "doctor/patient_test_file_view.html",
        title=f"Report: {file.file_name}",
        file=file,
        patient=patient,
    )


@doctor.route("/dashboard/doctor/patients/<patient_id>/test_files/<file_id>/download")
@login_required
def download_patient_test_file(patient_id, file_id):
    if current_user.role != "Doctor":
        abort(403)

    file: Medical_Report_Files = Medical_Report_Files.query.filter(
        Medical_Report_Files.file_id == int(file_id)
    ).first_or_404()

    file_name = f"{file.file_name}_{file.file_path_name}"
    return send_file(
        os.path.join(
            current_app.root_path,
            "static/upload/manager/test_results/",
            file.file_path_name,
        ),
        download_name=file_name,
        as_attachment=True,
    )


@doctor.route("/dashboard/doctor/patients/<patient_id>/records/<file_id>")
@login_required
def view_patient_record_file(patient_id, file_id):
    if current_user.role != "Doctor":
        abort(403)

    patient = Patients.query.filter(Patients.p_id == int(patient_id)).first_or_404()
    file: Patient_Record_Files = Patient_Record_Files.query.filter(

src/templates/doctor/includes/appointment_view_js.html
<script>
    let toastLive;
    let toastBootstrap;
    let rowId;
    $(document).ready(function () {
        $("#navAppt").removeClass("text-info");
        $("#navAppt").addClass("active");

        toastLive = document.getElementById('liveToast');
        toastBootstrap = bootstrap.Toast.getOrCreateInstance(toastLive);
        // Load items and extras
        $.ajax({
            type: "GET",
            url: "{{ url_for('api.prescription_items', pres_id=appt.prescription_id) }}",
            success: function (response) {
                if (response[0]["result"] == "success") {
                    $.each(response[1]["items"], function (index, item) {
                        data = `
                        <tr id="item${item.id}">
                            <td>${item.medicine}</td>
                            <td>${item.dosage}</td>
                            <td>${item.instruction}</td>
                            <td>${item.duration}</td>
                            <td>
                                <button type="button" id="btn_edit${item.id}" class="btn_edit btn btn-sm btn-secondary">
                                    <i class="bi bi-pencil-square"></i>
                                </button>
                                <button type="button" id="btn_delete${item.id}" class="btn_delete btn btn-sm btn-danger">
                                    <i class="bi bi-trash"></i>
                                </button>
                            </td>
                        </tr>
                         `
                        $("#item_list").append(data);
                    });
                    // Extras
                    var extras = response[2]["extras"];
                    $("#diag_info").html(extras.diagnosis);
                    $("#note_info").html(extras.notes);
                    $("#meet_info").html(extras.next_meet);
                }
            }
        });
        // New item add handler
        $("#pres_item_form").submit(function (e) {
            e.preventDefault();
            var data = $(this).serialize();
            $.ajax({
                type: "post",
                url: "{{ url_for('doctor.add_prescription_item', prescription_id=appt.prescription_id)}}",
                data: data,
                success: function (response) {
                    if (response["result"] == "success") {
                        // Clear all fields of the form
                        $("#pres_item_form")[0].reset();
                        data = `
                        <tr id="item${response["id"]}">
                            <td>${response["medicine"]}</td>
                            <td>${response["dosage"]}</td>
                            <td>${response["instruction"]}</td>
                            <td>${response["duration"]}</td>
                            <td>
                                <button type="button" id="btn_edit${response["id"]}" class="btn_edit btn btn-sm btn-secondary">
                                    <i class="bi bi-pencil-square"></i>
                                </button>
                                <button type="button" id="btn_delete${response["id"]}" class="btn_delete btn btn-sm btn-danger">
                                    <i class="bi bi-trash"></i>
                                </button>
                            </td>
                        </tr>
                         `
                        $("#item_list").append(data);
                    }
                    $("#toastMsg").removeClass("text-bg-danger");
                    $("#toastMsg").addClass("text-bg-success");
                    $("#toastMsg").html("New Prescription Item Added!");
                    toastBootstrap.show();
                    $("#add_pres_item_modal").modal("toggle");
                },
                error: function (error) {
                    $("#toastMsg").removeClass("text-bg-success");
                    $("#toastMsg").addClass("text-bg-danger");
                    $("#toastMsg").html("Server error, try again!");
                    toastBootstrap.show();
                    $("#add_pres_item_modal").modal("toggle");
                }
            });
        });
        // event listener to edit btn
        $("#item_list").on("click", ".btn_edit", function () {
            // Extract the row ID from the edit button's ID
            rowId = $(this).attr("id").replace("btn_edit", "");
            // Find the corresponding td elements and get their values
            var medicine = $("#item" + rowId + " td:nth-child(1)").text();
            var dosage = $("#item" + rowId + " td:nth-child(2)").text();
            var instruction = $("#item" + rowId + " td:nth-child(3)").text();
            var duration = $("#item" + rowId + " td:nth-child(4)").text();
            // Populate the modal form fields with the extracted information
            $("#edit_medicine").val(medicine);
            $("#edit_dosage").val(dosage);
            $("#edit_instruction").val(instruction);
            $("#edit_duration").val(duration);
            // Show the modal
            $("#edit_pres_item_modal").modal("show");
        });
        // Submit edit form
        $("#pres_item_edit_form").submit(function (e) {
            e.preventDefault();
            var data = $(this).serialize();
            var url = "/dashboard/doctor/prescription/{{ appt.prescription_id }}/edit_pitem/" + parseInt(rowId)
            $.ajax({
                type: "post",
                url: url,
                data: data,
                success: function (response) {
                    if (response["result"] == "success") {
                        data = `
                            <td>${response["medicine"]}</td>
                            <td>${response["dosage"]}</td>
                            <td>${response["instruction"]}</td>
                            <td>${response["duration"]}</td>
                            <td>
                                <button type="button" id="btn_edit${response["id"]}" class="btn_edit btn btn-sm btn-secondary">
                                    <i class="bi bi-pencil-square"></i>
                                </button>
                                <button type="button" id="btn_delete${response["id"]}" class="btn_delete btn btn-sm btn-danger">
                                    <i class="bi bi-trash"></i>
                                </button>
                            </td>
                         `
                        $('#item' + response["id"]).html(data);
                    };

                    $("#toastMsg").removeClass("text-bg-danger");
                    $("#toastMsg").addClass("text-bg-success");
                    $("#toastMsg").html("Prescription Item Updated!");
                    toastBootstrap.show();
                    $("#edit_pres_item_modal").modal("toggle");
                },
                error: function (error) {
                    $("#toastMsg").removeClass("text-bg-success");
                    $("#toastMsg").addClass("text-bg-danger");
                    $("#toastMsg").html("Server error, try again!");
                    toastBootstrap.show();
                    $("#edit_pres_item_modal").modal("toggle");
                }
            });
        });
        // event listener to delete btn
        $("#item_list").on("click", ".btn_delete", function () {
            // Extract the row ID from the delete button's ID
            rowId = $(this).attr("id").replace("btn_delete", "");
            var url = "/dashboard/doctor/prescription/{{ appt.prescription_id }}/delete_pitem/" + parseInt(rowId)
            $.ajax({
                type: "DELETE",
                url: url,
                success: function (response) {
                    if (response == "success") {
                        $("#item" + rowId).remove();
                        $("#toastMsg").removeClass("text-bg-danger");
                        $("#toastMsg").addClass("text-bg-success");
                        $("#toastMsg").html("Prescription Item Removed!");
                        toastBootstrap.show();
                    }
                }
            });
        });
        // Diagnosis btn
        $("#diag_info_btn").click(function (e) { 
            $("#diag_info").hide();
            $("#diag_info_btn").hide();
            $("#diag_info_save_btn").show();
            $("#diag_info_box").show();
            $("#diag_info_box").focus();

            $("#diag_info_box").val($("#diag_info").text());
        });
        // Note btn
        $("#note_info_btn").click(function (e) { 
            $("#note_info").hide();
            $("#note_info_btn").hide();
            $("#note_info_save_btn").show();
            $("#note_info_box").show();
            $("#note_info_box").focus();

            $("#note_info_box").val($("#note_info").text());
        });
        // Meet btn
        $("#meet_info_btn").click(function (e) { 
            $("#meet_info").hide();
            $("#meet_info_btn").hide();
            $("#meet_info_save_btn").show();
            $("#meet_info_box").show();
            $("#meet_info_box").focus();

            $("#meet_info_box").val($("#meet_info").text());
        });
    });

    function update_diagnosis() {
        // Diagnosis save btn
        $("#diag_info").show();
        $("#diag_info_btn").show();
        $("#diag_info_save_btn").hide();
        $("#diag_info_box").hide();
        $("#diag_info").html($("#diag_info_box").val());
        $.ajax({
            type: "POST",
            url: "{{ url_for('doctor.update_prescription_diagnosis', prescription_id=appt.prescription_id) }}",
            data: {
                diag: $("#diag_info_box").val()
            },
            success: function (response) {
                $("#toastMsg").removeClass("text-bg-danger");
                $("#toastMsg").addClass("text-bg-success");
                $("#toastMsg").html("Diagnosis information updated!");
                toastBootstrap.show();
            }
        });
    }
    function update_note() {
        // Note save btn
        $("#note_info").show();
        $("#note_info_btn").show();
        $("#note_info_save_btn").hide();
        $("#note_info_box").hide();
        $("#note_info").html($("#note_info_box").val());
        $.ajax({
            type: "POST",
            url: "{{ url_for('doctor.update_prescription_notes', prescription_id=appt.prescription_id) }}",
            data: {
                notes: $("#note_info_box").val()
            },
            success: function (response) {
                $("#toastMsg").removeClass("text-bg-danger");
                $("#toastMsg").addClass("text-bg-success");
                $("#toastMsg").html("Prescription note updated!");
                toastBootstrap.show();
            }
        });
    }
    function update_meet() {
        // Note save btn
        $("#meet_info").show();
        $("#meet_info_btn").show();
        $("#meet_info_save_btn").hide();
        $("#meet_info_box").hide();
        $("#meet_info").html($("#meet_info_box").val());
        $.ajax({
            type: "POST",
            url: "{{ url_for('doctor.update_prescription_nextmeet', prescription_id=appt.prescription_id) }}",
            data: {
                meet: $("#meet_info_box").val()
            },
            success: function (response) {
                $("#toastMsg").removeClass("text-bg-danger");
                $("#toastMsg").addClass("text-bg-success");
                $("#toastMsg").html("Next meeting information updated!");
                toastBootstrap.show();
            }
        });
    }
</script>

src/templates/doctor/includes/patient_medical_records.html
<div class="fs-4 fw-semibold mb-2">Medical Records</div>

{% if files.total != 0 %}
<table class="table table-striped border">
    <thead>
        <tr>
            <th class="text-start">#</th>
            <th class="text-start">Description</th>
            <th>File Size</th>
            <th>Upload Date</th>
            <th class="text-end">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for file in files %}
        <tr>
            <td class="text-start fw-light">{{ loop.index }}</td>
            <td class="text-start fw-light">{{ file.file_name }}</td>
            <td class="fw-light">{{ file.file_size_kb }} KB</td>
            <td class="fw-light">{{ file.upload_date }}</td>
            <td class="text-end">
                <!-- View -->
                <a href="{{ url_for('doctor.view_patient_record_file', patient_id=patient.p_id, file_id=file.file_id)}}"
                    class="btn btn-sm btn-secondary fw-light">
                    <i class="bi bi-eye-fill"></i>
                </a>
                <!-- Download -->
                <a href="{{ url_for('doctor.download_patient_record_file', patient_id=patient.p_id, file_id=file.file_id) }}"
                    class="btn btn-sm btn-success fw-light">
                    <i class="bi bi-download"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<div class="alert alert-warning" role="alert">
    No records found!
</div>
{% endif %}

<!-- Pagination -->
<div class="border rounded d-flex justify-content-center">
    {% for page_num in files.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
    {% if files.page == page_num %}
    <a class="btn btn-sm btn-info m-2"
        href="{{ url_for('doctor.view_patient', patient_id=patient.p_id, page=page_num) }}"
        id="pg_link{{ page_num }}">
        {{ page_num }}
    </a>
    {% else %}
    <a class="btn btn-sm btn-outline-info m-2"
        href="{{ url_for('doctor.view_patient', patient_id=patient.p_id, page=page_num) }}"
        id="pg_link{{ page_num }}">
        {{ page_num }}
    </a>
    {% endif %}
    {% else %}
    <button class="btn btn-sm btn-outline-secondary m-2" disabled>
        ...
    </button>
    {% endif %}
    {% endfor %}
</div>